# Install mx-creative-controller as Windows Scheduled Tasks that auto-start
# on user logon. Requires admin (Scheduled Task registration is privileged).
#
# Usage:
#   .\install.ps1            # build + register, but don't start now
#   .\install.ps1 -StartNow  # also kill any dev (tsx) processes and start the tasks
#
[CmdletBinding()]
param(
    [switch]$StartNow
)

$ErrorActionPreference = 'Stop'

# Self-elevate.
$principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host 'Requires admin — relaunching elevated...' -ForegroundColor Yellow
    $args = if ($StartNow) { '-StartNow' } else { '' }
    Start-Process powershell -Verb RunAs -ArgumentList '-NoProfile','-ExecutionPolicy','Bypass','-File',"`"$PSCommandPath`"",$args
    exit
}

$Root = $PSScriptRoot
$LogsDir = Join-Path $Root 'logs'
if (-not (Test-Path $LogsDir)) { New-Item -ItemType Directory -Path $LogsDir | Out-Null }

# Resolve node.exe (must be on PATH or in nvm's currently-active version).
$nodeCmd = Get-Command node.exe -ErrorAction SilentlyContinue
if (-not $nodeCmd) { throw 'node.exe not found on PATH. Install Node 22 LTS or newer and re-run.' }
$nodeExe = $nodeCmd.Source
Write-Host "node: $nodeExe"

function Build-Package($name) {
    $dir = Join-Path $Root $name
    Write-Host ""
    Write-Host "==> Building $name" -ForegroundColor Cyan
    Push-Location $dir
    try {
        npm install
        if ($LASTEXITCODE -ne 0) { throw "npm install failed in $name" }
        npm run build
        if ($LASTEXITCODE -ne 0) { throw "npm run build failed in $name" }
    } finally { Pop-Location }
}

Build-Package 'sidecar'
Build-Package 'keypad'

function Register-Task($name, $workdir, $logfile, $launcherPath) {
    Write-Host ""
    Write-Host "==> Registering Scheduled Task: $name" -ForegroundColor Cyan

    # Per-task PowerShell launcher. Start-Process -RedirectStandardOutput
    # avoids the exclusive write-lock that PowerShell's *>> takes for the
    # entire script lifetime (lock leaks blocked restart attempts).
    #
    # PID-file single-instance guard: Stop-ScheduledTask kills this launcher
    # but NOT the detached node child. Without the guard, every restart
    # stacked another instance — duplicate keypads fight over the HID device,
    # duplicate sidecars fight over the port (and the NEW one loses).
    $logErr  = $logfile -replace '\.log$', '.err'
    $pidFile = $logfile -replace '\.log$', '.pid'
    $launcher = @"
`$ErrorActionPreference = 'Stop'
`$pidFile = '$pidFile'
if (Test-Path `$pidFile) {
    `$oldPid = [int](Get-Content `$pidFile -ErrorAction SilentlyContinue | Select-Object -First 1)
    `$old = Get-Process -Id `$oldPid -ErrorAction SilentlyContinue
    if (`$old -and `$old.ProcessName -eq 'node') {
        `$old | Stop-Process -Force
        Start-Sleep -Milliseconds 500
    }
}
`$proc = Start-Process -FilePath '$nodeExe' ``
    -ArgumentList 'dist\index.js' ``
    -WorkingDirectory '$workdir' ``
    -RedirectStandardOutput '$logfile' ``
    -RedirectStandardError  '$logErr' ``
    -NoNewWindow -PassThru
Set-Content -Path `$pidFile -Value `$proc.Id
`$proc.WaitForExit()
exit `$proc.ExitCode
"@
    Set-Content -Path $launcherPath -Value $launcher -Encoding UTF8

    # VBS shim. powershell.exe -WindowStyle Hidden flashes a console window
    # at boot before the hide kicks in (you'd see a couple of empty terminals
    # appear briefly on logon). wscript.exe + WshShell.Run with windowStyle=0
    # is honored from the very first instant — truly no window.
    $vbsPath = [System.IO.Path]::ChangeExtension($launcherPath, '.vbs')
    $psPathLiteral = $launcherPath -replace '"', '""'
    $vbs = @"
' Auto-generated by install.ps1. Runs the per-task .ps1 launcher with a
' truly hidden window (no flash, no taskbar entry).
Dim shell, exitCode
Set shell = CreateObject("WScript.Shell")
exitCode = shell.Run("powershell.exe -NoProfile -ExecutionPolicy Bypass -File ""$psPathLiteral""", 0, True)
WScript.Quit exitCode
"@
    # wscript.exe chokes on a BOM at the start of a .vbs file with
    # "error: invalid character code 800A0408" — write without BOM.
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($vbsPath, $vbs, $utf8NoBom)

    $action = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument "`"$vbsPath`""

    $trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME

    $settings = New-ScheduledTaskSettingsSet `
        -AllowStartIfOnBatteries `
        -DontStopIfGoingOnBatteries `
        -StartWhenAvailable `
        -RestartCount 999 `
        -RestartInterval (New-TimeSpan -Minutes 1) `
        -ExecutionTimeLimit (New-TimeSpan -Days 365) `
        -MultipleInstances IgnoreNew `
        -Hidden

    # Run as the current user, only when logged on.
    $principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive -RunLevel Limited

    Register-ScheduledTask -TaskName $name -Action $action -Trigger $trigger -Settings $settings -Principal $principal -Force | Out-Null
    Write-Host "    registered."
}

$LaunchersDir = Join-Path $Root 'launchers'
if (-not (Test-Path $LaunchersDir)) { New-Item -ItemType Directory -Path $LaunchersDir | Out-Null }

$sidecarLog      = Join-Path $LogsDir 'sidecar.log'
$keypadLog       = Join-Path $LogsDir 'keypad.log'
$sidecarLauncher = Join-Path $LaunchersDir 'run-sidecar.ps1'
$keypadLauncher  = Join-Path $LaunchersDir 'run-keypad.ps1'

Register-Task 'mx-sidecar' (Join-Path $Root 'sidecar') $sidecarLog $sidecarLauncher
Register-Task 'mx-keypad'  (Join-Path $Root 'keypad')  $keypadLog  $keypadLauncher

Write-Host ""
Write-Host 'Installed.' -ForegroundColor Green
Write-Host "Logs: $LogsDir"
Write-Host ''

if ($StartNow) {
    Write-Host '==> -StartNow: stopping any dev (tsx) node processes, then starting tasks' -ForegroundColor Cyan
    # Kill node processes spawned by our launchers. Start-Process strips the
    # absolute path from the child's CommandLine, so we match by ancestor:
    # a node whose parent (or grandparent) PowerShell is running one of our
    # launcher scripts.
    Get-CimInstance Win32_Process -Filter "Name='node.exe'" | ForEach-Object {
        $node = $_
        $walk = $node.ParentProcessId
        for ($i = 0; $i -lt 4 -and $walk -gt 0; $i++) {
            $p = Get-CimInstance Win32_Process -Filter "ProcessId=$walk" -ErrorAction SilentlyContinue
            if (-not $p) { break }
            if ($p.CommandLine -like "*$Root\launchers*" -or $p.CommandLine -like "*Hardware-interface*launchers*") {
                Write-Host "    killing node pid $($node.ProcessId) (launched by our task)"
                Stop-Process -Id $node.ProcessId -Force -ErrorAction SilentlyContinue
                break
            }
            $walk = $p.ParentProcessId
        }
    }
    # Also kill any leftover PowerShell launcher processes still holding log
    # file handles, so the next start can write logs cleanly.
    Get-CimInstance Win32_Process -Filter "Name='powershell.exe'" | Where-Object {
        $_.CommandLine -like "*Hardware-interface*launchers*"
    } | ForEach-Object {
        Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue
    }
    Start-Sleep -Seconds 1
    Start-ScheduledTask -TaskName 'mx-sidecar'
    Start-ScheduledTask -TaskName 'mx-keypad'
    Write-Host 'Tasks started.' -ForegroundColor Green
} else {
    Write-Host 'Tasks will auto-start on next logon.'
    Write-Host 'To start now without logging out, run: .\install.ps1 -StartNow'
}
